# Getting started with Numpy 

Numpy is simply a Linear Algebra Library for Python. It is so important for Data Science with Python because almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks. Because of it bindings to C libraries, Numpy is incredibly fast. You might want to check out [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists) for more information on why you should use Arrays instead of lists.

I will only show you the basics of Numpy starting from how to get it installed on your local machine!

## Installing Numpy on your local machine  

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you already have Anaconda on your machine, you can  install Numpy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you don't already have Anaconda and can not install it, please visit [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you are able to install Numpy, you can import it as you would any other Python library:

In [36]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

Numpy arrays basically come in two forms: vectors and matrices. Vectors are strictly 1-d arrays while matrices are 2-d (but you should note a matrix can still have only one row or one column).

We will begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

A Numpy array can be created an array by directly converting a list or list of lists:

In [37]:
my_list = [1,2,3,3,4,5]
my_list

[1, 2, 3, 3, 4, 5]

In [38]:
np.array(my_list)

array([1, 2, 3, 3, 4, 5])

In [39]:
matrix = [[5,6,7],[8,9,10],[11,12,13]]
matrix

[[5, 6, 7], [8, 9, 10], [11, 12, 13]]

In [40]:
np.array(matrix)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

## Built-in Methods

There are lots of built-in methods to generate Arrays

### arange

This method return evenly spaced values within a given interval.

In [41]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

### zeros and ones

This method generate arrays of zeros or ones

In [43]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [46]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
This method return evenly spaced numbers over a specified interval.

In [47]:
np.linspace(0,15,2)

array([ 0., 15.])

In [48]:
np.linspace(0,15,25)

array([ 0.   ,  0.625,  1.25 ,  1.875,  2.5  ,  3.125,  3.75 ,  4.375,
        5.   ,  5.625,  6.25 ,  6.875,  7.5  ,  8.125,  8.75 ,  9.375,
       10.   , 10.625, 11.25 , 11.875, 12.5  , 13.125, 13.75 , 14.375,
       15.   ])

## eye

This method creates an identity matrix

In [49]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

## Random 

Numpy also provide lots of methods to create random number arrays:

### rand
This create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [50]:
np.random.rand(5)

array([0.1244161 , 0.03531669, 0.64012568, 0.92262628, 0.21225439])

In [51]:
np.random.rand(3,3)

array([[0.98787148, 0.16247212, 0.05491741],
       [0.70112983, 0.70794214, 0.28197339],
       [0.65396801, 0.95951156, 0.80035947]])

### randn

This return a sample from the "standard normal" distribution. Unlike rand which is uniform:

In [52]:
np.random.randn(5)

array([-0.21364766,  0.18151918,  0.44829622, -2.33361723,  0.19787448])

In [53]:
np.random.randn(3,3)

array([[-0.65431138, -0.34201422,  0.57891091],
       [-0.13762914, -0.16814631,  0.25231098],
       [ 0.80271844,  0.95454973,  0.23905086]])

### randint
This return random integers from `low` (inclusive) to `high` (exclusive).

In [54]:
np.random.randint(1,50)

7

In [55]:
np.random.randint(1,50,5)

array([40, 33, 46, 13, 14])

## Array Attributes and Methods

Below are some useful attributes and methods or an array:

In [56]:
array1 = np.arange(15)
array2 = np.random.randint(0,50,15)

In [57]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
array2

array([26, 10,  6, 40, 32, 45, 37, 20, 12, 20,  6, 44, 16, 45, 36])

## Reshape
This method returns an array containing the same data with a new shape.

In [59]:
array1.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [60]:
array2

array([26, 10,  6, 40, 32, 45, 37, 20, 12, 20,  6, 44, 16, 45, 36])

In [61]:
array2.max()

45

In [62]:
array2.argmax()

5

In [63]:
array2.min()

6

In [64]:
array2.argmin()

2

## Shape

Shape is an attribute that arrays have (not a method):

In [65]:
# Vector
array1.shape

(15,)

In [66]:
# Notice the two sets of brackets
array1.reshape(1,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [67]:
array1.reshape(1,15).shape

(1, 15)

In [68]:
array1.reshape(15,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [69]:
array1.reshape(15,1).shape

(15, 1)

### dtype

You can also grab the data type of the object in the array:

In [70]:
array1.dtype

dtype('int32')